%YAML 1.2
---

# host infos
host_string: '10.73.73.69'
host_port: '9090'
host_user: 'root'
host_pass: 'redhat'

# manually configured selenium hub
selenium_hub: ''

# avocado config
avocado_results_dir: '/home/weiwang/work_auto/avocado-results/'

# versions of pkg/sys under test
test_pkg_ver: 'cockpit-ovirt-dashboard-0.15.1-2.el8ev.noarch'
test_sys_ver: 'rhvh-4.4.8.1-0.20210903.0'